### PR TITLE
Fix Page stats checkbox

### LINKED ISSUE #61: [Bug] Page-stats Checkbox not accurate
As promised, I was working on adding the number of pages today. While focusing on the page-related logic and iterating through the setup, I noticed an inconsistency: the "Page stats" checkbox (column index) is checked, but the actual Parquet file contains no page-level statistics.

I intentionally created the Parquet files without page stats(, since cuDF doesn’t stably support page-level pruning yet). However, the checkbox state doesn’t reflect that, which could be misleading.

Here’s what I’m referring to—this is from the current online version:

Image

### PR DESCRIPTION
**Pull request by JigaoLuo**
Close #61

This PR updates the logic of the checkbox, which should now accurately represent the presence of page stats c.f. the image shown in the issue.

image

### CODE REVIEW

File: src/parquet_ctx.rs [hunk 1]
```diff
@@ -57,8 +57,15 @@ impl MetadataDisplay {
 
         let has_column_index = metadata
             .column_index()
-            .and_then(|ci| ci.first().map(|c| !c.is_empty()))
```
Comment (JigaoLuo) [inline src/parquet_ctx.rs:60]: I added an image in the PR page to prove this condition is not enough

**Comment by XiangpengHao** [comment]
> And there is a logging why the previous `is_empty` check is not enough:
> 
> swappy-20250919_215308

This is a great observation. I feel we probably can also do something in upstream to make this more intuitive.

**Review by XiangpengHao — APPROVED** [review]
Thank you @JigaoLuo

**Comment by JigaoLuo** [comment]
> I feel we probably can also do something in upstream to make this more intuitive.

Not sure I fully get your suggestion. Upstream logic is around here: https://github.com/apache/arrow-rs/blob/13fb04118a4b641ea5825c9abab4e2df9cab407e/parquet/src/file/metadata/mod.rs#L384-L387

Are you proposing we find a better and more intuitive way to inform users when `column_index` is empty?
